name: Android CI (Clean Build)

on:
  push:
    branches:
      - main
      - master
      - fix/**
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    name: Build Debug APK
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout source code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup JDK 17 (Android Gradle Plugin butuh min 17)
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle

      # 3️⃣ Set permission Gradle wrapper (kadang error kalau gak ada izin)
      - name: Make gradlew executable
        run: chmod +x gradlew

      # 4️⃣ Bersihin build lama biar gak bentrok (ini penting banget buat bug reordering lo)
      - name: Clean Gradle build
        run: ./gradlew clean

      # 5️⃣ Build aplikasi (Debug)
      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace

      # 6️⃣ Simpan hasil build (artifact)
      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: ViMusic-Debug-APK
          path: app/build/outputs/apk/debug/app-debug.apk

  # Optional: lint/verify step (bisa dihapus kalau mau build doang)
  verify:
    name: Run Lint & Tests
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle

      - name: Run Lint (non-blocking)
        continue-on-error: true
        run: ./gradlew lint

      - name: Run Unit Tests
        continue-on-error: true
        run: ./gradlew test --stacktrac
