name: Android CI (Release Build)

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    name: Build Release APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Clean Gradle build
        run: ./gradlew clean

      - name: Build Release APK
        run: ./gradlew assembleRelease --stacktrace

      - name: List APK outputs
        run: |
          echo "Checking build outputs..."
          ls -R app/build/outputs || echo "No outputs found"

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: ViMusic-Release-APK
          path: app/build/outputs/apk/**/*.apk
