name: Android CI - Releas

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_HOME: /usr/local/lib/android/sdk

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Restore Gradle cache (optional)
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: Decode keystore from secret
        run: |
          echo "KEYSTORE_BASE64" | base64 --decode > ./my-release-key.keystore
          ls -l my-release-key.keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}

      - name: Clean
        run: ./gradlew clean

      - name: Build Release APK (signed)
        run: ./gradlew assembleRelease \
          -Pandroid.injected.signing.store.file=my-release-key.keystore \
          -Pandroid.injected.signing.store.password="${KEYSTORE_PASSWORD}" \
          -Pandroid.injected.signing.key.alias="${KEY_ALIAS}" \
          -Pandroid.injected.signing.key.password="${KEY_PASSWORD}"
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Upload signed Release APK
        uses: actions/upload-artifact@v4
        with:
          name: ViMusic-Release-APK
          path: app/build/outputs/apk/release/*.apk
