name: Android CI (Release Build)

on:
  push:
    branches:
      - main
      - master
      - release/**
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    name: Build Release APK
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup JDK 17 (dibutuhkan Android Gradle Plugin modern)
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle

      # 3️⃣ Pastikan gradlew bisa dieksekusi
      - name: Make gradlew executable
        run: chmod +x gradlew

      # 4️⃣ Bersihin build lama biar gak bentrok
      - name: Clean Gradle build
        run: ./gradlew clean

      # 5️⃣ Build APK Release
      - name: Build Release APK
        run: ./gradlew assembleRelease --stacktrace

      # 6️⃣ Upload hasil build ke artifacts
      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: ViMusic-Release-v0.1.4
          path: app/build/outputs/apk/release/app-release.apk

  # (Opsional) Jalankan lint & test
  verify:
    name: Run Lint & Tests
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle

      - name: Run Lint (non-blocking)
        continue-on-error: true
        run: ./gradlew lint

      - name: Run Unit Tests
        continue-on-error: true
        run: ./gradlew test --stacktrace
